computers/urls.py
from django.urls import path
from .views import *

app_name = 'comp'

urlpatterns = [
    path('accessories/', AccessoriesListView.as_view(), name='accessories'),
    path('accessories/<int:pk>/', AccessoriesDetailView.as_view(), name='accessories-detail'),
    path('phones/<int:pk>/', ComputerDetailView.as_view(), name='computers-detail'),
    path('', ComputerListView.as_view(), name='computer'),
]

pages/urls.py
from django.urls import path
from pages.views import HomeTemplateViews, ContactCreateViews

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactCreateViews.as_view(), name='contact'),
    path('', HomeTemplateViews.as_view(), name='home'),
]

phones/urls.py
from django.urls import path
from .views import *

app_name = 'phones'

urlpatterns = [
    path('accessories/', AccessoriesListView.as_view(), name='accessories'),
    path('phones/', PhoneListView.as_view(), name='phone'),
    path('accessories/<int:pk>/', AccessoriesDetailView.as_view(), name='accessories-detail'),
    path('phones/<int:pk>/', PhoneDetailView.as_view(), name='phone-detail'),
]

turbogaming1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('computers/', include('computers.urls', namespace='comp')),
    path('phone/', include('phones.urls', namespace='phones')),
    path('', include('pages.urls', namespace='pages'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/footer.html
{% load static %}
<footer class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 class="footer_title">About Us</h6>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                        labore dolore magna aliqua.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6 class="footer_title">Newsletter</h6>
                    <p>Stay updated with our latest trends</p>
                    <div id="mc_embed_signup">
                        <form target="_blank"
                              action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                              method="get" class="subscribe_form relative">
                            <div class="input-group d-flex flex-row">
                                <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Email Address '" required="" type="email">
                                <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
                            </div>
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget instafeed">
                    <h6 class="footer_title">Instagram Feed</h6>
                    <ul class="list instafeed d-flex flex-wrap">
                        <li><img src="{% static 'img/instagram/Image-01.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-02.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-03.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-04.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-05.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-06.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-07.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/instagram/Image-07.jpg' %}" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget f_social_wd">
                    <h6 class="footer_title">Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="f_social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row footer-bottom d-flex justify-content-between align-items-center">
            <p class="col-lg-12 footer-text text-center">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                    href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
        </div>
    </div>
</footer>

templates/layouts/header.html
{% load static %}

<header class="header_area">
    <!--           	<div class="top_menu row m0">-->
    <!--           		<div class="container">-->
    <!--					<div class="float-left">-->
    <!--						<a href="mailto:support@colorlib.com">support@colorlib.com</a>-->
    <!--						<a href="#">Welcome to Catalouge</a>-->
    <!--					</div>-->
    <!--					<div class="float-right">-->
    <!--						<ul class="header_social">-->
    <!--							<li><a href="#"><i class="fa fa-facebook"></i></a></li>-->
    <!--							<li><a href="#"><i class="fa fa-twitter"></i></a></li>-->
    <!--							<li><a href="#"><i class="fa fa-dribbble"></i></a></li>-->
    <!--							<li><a href="#"><i class="fa fa-behance"></i></a></li>-->
    <!--						</ul>-->
    <!--					</div>-->
    <!--           		</div>	-->
    <!--           	</div>	-->
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand logo_h" href="index.html"><img
                        src="{% static 'img/clients-logo/logoza.ru%20(1).png' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
                        <li class="nav-item active"><a class="nav-link" href="{% url 'pages:home' %}">Home</a></li>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="{% url 'phones:phone' %}">Phone</a>
                                <li class="nav-item"><a class="nav-link" href="{% url 'phones:accessories' %}">Phone Accessories</a>
                                <li class="nav-item"><a class="nav-link" href="{% url 'comp:computer' %}">Computer</a>
                                <li class="nav-item"><a class="nav-link" href="{% url 'comp:accessories' %}">Computer Accessories</a>

                            </ul>
                        </li>
                        <li class="nav-item submenu dropdown">
                            <a href="blog.html" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">Blog</a>
                        <li class="nav-item submenu dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">Pages</a>
                            <ul class="dropdown-menu">
{#                                <li class="nav-item"><a class="nav-link" href="login.html">Login</a>#}
{#                                <li class="nav-item"><a class="nav-link" href="tracking.html">Tracking</a>#}
{#                                <li class="nav-item"><a class="nav-link" href="elements.html">Elements</a></li>#}
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'pages:contact' %}">Contact</a></li>
                        <div>
                            {% if request.user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}">Log out</a></li>
                            {% else %}
                                <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}">Sign in</a></li>
                            {% endif %}
                        </div>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item"><a href="#" class="cart"><i class="lnr lnr lnr-cart"></i></a></li>
                        <li class="nav-item"><a href="#" class="search"><i class="lnr lnr-magnifier"></i></a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>