computers/urls.py
from django.urls import path
from .views import *

app_name = 'comp'

urlpatterns = [
    path('accessories/', AccessoriesListView.as_view(), name='accessories'),
    path('accessories/<int:pk>/', AccessoriesDetailView.as_view(), name='accessories-detail'),
    path('phones/<int:pk>/', ComputerDetailView.as_view(), name='computers-detail'),
    path('', ComputerListView.as_view(), name='computer'),
]

pages/urls.py
from django.urls import path
from pages.views import HomeTemplateViews, ContactCreateViews

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactCreateViews.as_view(), name='contact'),
    path('', HomeTemplateViews.as_view(), name='home'),
]

phones/urls.py
from django.urls import path
from .views import *

app_name = 'phones'

urlpatterns = [
    path('accessories/', AccessoriesListView.as_view(), name='accessories'),
    path('phones/', PhoneListView.as_view(), name='phone'),
    path('accessories/<int:pk>/', AccessoriesDetailView.as_view(), name='accessories-detail'),
    path('phones/<int:pk>/', PhoneDetailView.as_view(), name='phone-detail'),
]

turbogaming1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
    path('computers/', include('computers.urls', namespace='comp')),
    path('phone/', include('phones.urls', namespace='phones')),
    path('', include('pages.urls', namespace='pages'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

computers/models.py
from django.db import models


class CategoryModel(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class BrandModel(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'


class ColorModel(models.Model):
    title = models.CharField(max_length=15, null=True, blank=True,)
    code = models.CharField(max_length=15,)
    created_at = models.DateTimeField(auto_now_add=True,)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'color'
        verbose_name_plural = 'colors'


class ComputerModel(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='phones')
    short_description = models.CharField(max_length=555)
    long_description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(CategoryModel,
                                 on_delete=models.PROTECT,
                                 related_name='phones',
                                 verbose_name='category'
                                 )
    brand = models.ForeignKey(BrandModel,
                              on_delete=models.PROTECT,
                              related_name='phones')
    colors = models.ManyToManyField(ColorModel, related_name='phones')
    CPU = models.CharField(max_length=255)
    GPU = models.CharField(max_length=255)
    RAM = models.CharField(max_length=255)
    SSD = models.CharField(max_length=255)
    built_in_memory = models.CharField(max_length=255)
    number_of_processor_cores = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Computer'
        verbose_name_plural = 'computers'


class AccessoriesModel(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='accessories')
    short_description = models.CharField(max_length=555)
    long_description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(CategoryModel,
                                 on_delete=models.PROTECT,
                                 related_name='accessories',
                                 verbose_name='category'
                                 )
    brand = models.ForeignKey(BrandModel,
                              on_delete=models.PROTECT,
                              related_name='accessories')
    colors = models.ManyToManyField(ColorModel, related_name='accessories')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'accessor'
        verbose_name_plural = 'accessories'

phones/models.py
from django.db import models


class CategoryModel(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class BrandModel(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'


class ColorModel(models.Model):
    title = models.CharField(max_length=15, null=True, blank=True,)
    code = models.CharField(max_length=15,)
    created_at = models.DateTimeField(auto_now_add=True,)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'color'
        verbose_name_plural = 'colors'


class PhoneModel(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='phones')
    short_description = models.CharField(max_length=555)
    long_description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(CategoryModel,
                                 on_delete=models.PROTECT,
                                 related_name='phones',
                                 verbose_name='category'
                                 )
    brand = models.ForeignKey(BrandModel,
                              on_delete=models.PROTECT,
                              related_name='phones')
    colors = models.ManyToManyField(ColorModel, related_name='phones')
    processor = models.CharField(max_length=255)
    GPU = models.CharField(max_length=255)
    RAM = models.CharField(max_length=255)
    built_in_memory = models.CharField(max_length=255)
    number_of_processor_cores = models.CharField(max_length=255)
    main_lens = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'phone'
        verbose_name_plural = 'phones'


class AccessoriesModel(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='accessories')
    short_description = models.CharField(max_length=555)
    long_description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(CategoryModel,
                                 on_delete=models.PROTECT,
                                 related_name='accessories',
                                 verbose_name='category'
                                 )
    brand = models.ForeignKey(BrandModel,
                              on_delete=models.PROTECT,
                              related_name='accessories')
    colors = models.ManyToManyField(ColorModel, related_name='accessories')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'accessor'
        verbose_name_plural = 'accessories'

computers/views.py
from django.views.generic import ListView, DetailView
from .models import *


class ComputerListView(ListView):
    template_name = 'computers.html'
    paginate_by = 9

    def get_queryset(self):
        qs = ComputerModel.objects.order_by('-pk')
        q = self.request.GET.get('q')

        cat = self.request.GET.get('cat')
        brand = self.request.GET.get('brand')
        color = self.request.GET.get('color')
        price = self.request.GET.get('price')

        if q:
            qs = qs.filter(title__icontains=q)

        if cat:
            qs = qs.filter(category__id=cat)

        if brand:
            qs = qs.filter(brand__id=brand)

        if color:
            qs = qs.filter(colors__id=color)

        if price:
            price = price.split(';')
            price_from, price_to = price
            qs = qs.filter(real_price__gte=price_from, real_price__lte=price_to)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        context['brands'] = BrandModel.objects.all()
        context['colors'] = ColorModel.objects.all()

        return context


class AccessoriesListView(ListView):
    template_name = 'accessoriescom.html'
    paginate_by = 9

    def get_queryset(self):
        qs = AccessoriesModel.objects.order_by('-pk')
        q = self.request.GET.get('q')

        cat = self.request.GET.get('cat')
        brand = self.request.GET.get('brand')
        color = self.request.GET.get('color')
        price = self.request.GET.get('price')

        if q:
            qs = qs.filter(title__icontains=q)

        if cat:
            qs = qs.filter(category__id=cat)

        if brand:
            qs = qs.filter(brand__id=brand)

        if color:
            qs = qs.filter(colors__id=color)

        if price:
            price = price.split(';')
            price_from, price_to = price
            qs = qs.filter(real_price__gte=price_from, real_price__lte=price_to)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        context['brands'] = BrandModel.objects.all()
        context['colors'] = ColorModel.objects.all()

        return context


class ComputerDetailView(DetailView):
    model = ComputerModel
    template_name = 'computer_detail.html'


class AccessoriesDetailView(DetailView):
    model = AccessoriesModel
    template_name = 'accessories_com_detail.html'

phones/views.py
from django.views.generic import ListView, DetailView
from .models import *


class PhoneListView(ListView):
    template_name = 'phones.html'
    paginate_by = 9

    def get_queryset(self):
        qs = PhoneModel.objects.order_by('-pk')
        q = self.request.GET.get('q')

        cat = self.request.GET.get('cat')
        brand = self.request.GET.get('brand')
        color = self.request.GET.get('color')
        price = self.request.GET.get('price')

        if q:
            qs = qs.filter(title__icontains=q)

        if cat:
            qs = qs.filter(category__id=cat)

        if brand:
            qs = qs.filter(brand__id=brand)

        if color:
            qs = qs.filter(colors__id=color)

        if price:
            price = price.split(';')
            price_from, price_to = price
            qs = qs.filter(real_price__gte=price_from, real_price__lte=price_to)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        context['brands'] = BrandModel.objects.all()
        context['colors'] = ColorModel.objects.all()

        return context


class AccessoriesListView(ListView):
    template_name = 'accessoriesmob.html'
    paginate_by = 9

    def get_queryset(self):
        qs = AccessoriesModel.objects.order_by('-pk')
        q = self.request.GET.get('q')

        cat = self.request.GET.get('cat')
        brand = self.request.GET.get('brand')
        color = self.request.GET.get('color')
        price = self.request.GET.get('price')

        if q:
            qs = qs.filter(title__icontains=q)

        if cat:
            qs = qs.filter(category__id=cat)

        if brand:
            qs = qs.filter(brand__id=brand)

        if color:
            qs = qs.filter(colors__id=color)

        if price:
            price = price.split(';')
            price_from, price_to = price
            qs = qs.filter(real_price__gte=price_from, real_price__lte=price_to)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = CategoryModel.objects.all()
        context['brands'] = BrandModel.objects.all()
        context['colors'] = ColorModel.objects.all()

        return context


class PhoneDetailView(DetailView):
    model = PhoneModel
    template_name = 'phone_detail.html'


class AccessoriesDetailView(DetailView):
    model = AccessoriesModel
    template_name = 'accessories_mob_detail.html'

templates/accessoriesmob.html
{% extends 'base.html' %}

{% block extra_css %}
    <style>
        a:hover {
            cursor: pointer;
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>
{% endblock %}

{% block content %}
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
				<div class="container">
					<div class="banner_content text-center">
						<h2>Shop Category Page</h2>
						<div class="page_link">
							<a href="{% url 'pages:home' %}">Home</a>
							<a href="#">Category</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Category Product Area =================-->
        <section class="cat_product_area p_120">
        	<div class="container">
        		<div class="row flex-row-reverse">
        			<div class="col-lg-9">
        				<div class="product_top_bar">
                            <div class="left_dorp">
                                <form class="form-inline">
                                    <div class="form-group mx-sm-3 mb-2">
                                        <label for="inputPassword2" class="sr-only">Search</label>
                                        <input name="q" type="text"  class="form-control" id="inputPassword2"
                                               placeholder="Search">
                                    </div>
                                    <button type="submit" class="btn btn-info mb-2">Search</button>
                                </form>
                            </div>


                            <div class="right_page ml-auto ">
								<nav class="cat_page" aria-label="Page navigation example">
									<ul class="pagination">
										<li class="page-item"><a class="page-link" href="#"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a></li>
										<li class="page-item active"><a class="page-link" href="#">1</a></li>
										<li class="page-item"><a class="page-link" href="#">2</a></li>
										<li class="page-item"><a class="page-link" href="#">3</a></li>
										<li class="page-item blank"><a class="page-link" href="#">...</a></li>
										<li class="page-item"><a class="page-link" href="#">6</a></li>
										<li class="page-item"><a class="page-link" href="#"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></li>
									</ul>
								</nav>
        					</div>
        				</div>

                        <div class="latest_product_inner row">
                            {% for i in object_list %}
                                <div class="col-lg-4 col-md-4 col-sm-6">
                                    <div class="f_p_item">
                                        <div class="f_p_img">
                                            <img class="img-fluid" src="{{ i.image.url }}" alt="">
                                            <div class="p_icon">
                                                <span class="label">Sale</span>
                                                <a href="#"><i class="lnr lnr-cart"></i></a>
                                            </div>
                                        </div>
                                        <a href="#"><h4>{{ i.title }}</h4></a>
                                        <h5>{{ i.price }}$</h5>
                                        <a href="{% url 'phones:accessories-detail' pk=i.pk %}">
                                            <button type="button" class="btn btn-primary float-right"> Batafsil</button>
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

        			</div>
        			<div class="col-lg-3">
        				<div class="left_sidebar_area">
        					<aside class="left_widgets cat_widgets">
        						<div class="l_w_title">
									<h3>Phones Categories</h3>
								</div>
                                {% for category in categories %}
                                    <div class="widgets_inner">
                                        <ul class="list">
                                            <li>
                                                <a {% if request.GET.cat == category.pk|stringformat:"i" %}style="color:#111"{% endif %}
                                                   onclick="addUrlParameter('cat', '{{ category.pk }}')">{{ category.title }}</a>
                                            </li>
                                        </ul>
                                    </div>
                                {% endfor %}
        					</aside>
        					<aside class="left_widgets p_filter_widgets">
        						<div class="l_w_title">
									<h3>Product Filters</h3>
								</div>
                                {% for brand in brands %}
                                    <div class="widgets_inner">
                                        <ul class="list">
                                            <li>
                                                <a {% if request.GET.cat == brand.pk|stringformat:"i" %}style="color:#111"{% endif %}
                                                   onclick="addUrlParameter('brand', '{{ brand.pk }}')">{{ brand.title }}</a>
                                            </li>
                                        </ul>
                                    </div>
                                {% endfor %}
        					</aside>
                            {% for color in colors %}
                                <label style="background: {{ color.code }}">
                                    <input onclick="addUrlParameter('color', '{{ color.pk }}')" type="radio"
                                           name="color"
                                           value="{{ color.pk }}">
                                </label>
                            {% endfor %}
        				</div>
        			</div>
                </div>
        	</div>
        </section>


        <!--================End Category Product Area =================-->
        
        <!--================Most Product Area =================-->
        <section class="most_product_area most_p_withoutbox">
			<div class="container">
				<div class="main_title">
					<h2>Most Searched Products</h2>
					<p>Who are in extremely love with eco friendly system.</p>
				</div>
				<div class="row most_product_inner">
					<div class="col-lg-3 col-sm-6">
						<div class="most_p_list">
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-1.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-2.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-3.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="most_p_list">
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-4.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-5.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-6.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="most_p_list">
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-7.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-8.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-9.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6">
						<div class="most_p_list">
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-10.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-11.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
							<div class="media">
								<div class="d-flex">
									<img src="img/product/most-product/m-product-12.jpg" alt="">
								</div>
								<div class="media-body">
									<a href="#"><h4>Black lace Heels</h4></a>
									<h3>$189.00</h3>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        </section>

{% block extra_js %}
    <script>
        function addUrlParameter(name, value) {
            let searchParams = new URLSearchParams(window.location.search)
            if (searchParams.has(name) && searchParams.get(name) === value) {
                searchParams.delete(name)
            } else {
                searchParams.set(name, value)
            }
            window.location.search = searchParams.toString()
        }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>#}
{#    <script>#}
{#        $(".js-range-slider").ionRangeSlider({#}
{#            type: "double",#}
{#            grid: true,#}
{#            min: {{ min_price }},#}
{#            max: {{ max_price }},#}
{#            from: {% get_price request 0 %},#}
{#            to: {% get_price request 1 %},#}
{#            prefix: "$",#}
{#            onFinish: function (data) {#}
{#                let from = data.from;#}
{#                let to = data.to;#}
{#                let result = from.toString() + ';' + to.toString()#}
{#                addUrlParameter('price', result);#}
{#            },#}
{#        });#}
{#    </script>#}
{% endblock %}


{% endblock %}
{#        						<div class="widgets_inner">#}
{#        							<h4>Price</h4>#}
{#        							<div class="range_item">#}
{#        								<div id="slider-range"></div>#}
{#										<div class="row m0">#}
{#											<label for="amount">Price : </label>#}
{#  											<input type="text" id="amount" readonly>#}
{#										</div>#}
{#									</div>#}
{#        						</div>#}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
        <title>ListAshop</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/jquery-ui/jquery-ui.css' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    </head>
    <body>
{% include 'layouts/header.html' %}

{% block content %} {% endblock %}

{% include 'layouts/footer.html' %}


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/stellar.js' %}"></script>
        <script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
        <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/isotope-min.js' %}"></script>
        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'vendors/counter-up/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'vendors/flipclock/timer.js' %}"></script>
        <script src="{% static 'vendors/counter-up/jquery.counterup.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/theme.js' %}"></script>
    </body>
</html>